---
plugins:
  duplication:
    enabled: true
    channel: swift-beta
  structure:
    enabled: true
    channel: swift-beta
exclude_patterns:
- "ReactiveCocoaTests/**/*"
- "ReactiveMapKitTests/**/*"
- "**/*.js"
